filepaths:
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P001/ses-S001/eeg/sub-P001_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "01"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P002/ses-S001/eeg/sub-P002_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "02"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P003/ses-S002/eeg/sub-P003_ses-S002_task-Default_run-001_eeg.xdf"
    subject_id: "03"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P004/ses-S001/eeg/sub-P004_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "04"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P005/ses-S001/eeg/sub-P005_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "05"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P006/ses-S001/eeg/sub-P001_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "06"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P007/ses-S002_Elbueno/eeg/sub-P007_ses-S002_task-Default_run-001_eeg.xdf"
    subject_id: "07"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P008/ses-S001/eeg/sub-P008_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "08"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P009/ses-S001/eeg/sub-P009_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "09"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P010/ses-S001/eeg/sub-P010_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "10"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P011/ses-S001/eeg/sub-P011_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "11"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P012/ses-S001/eeg/sub-P012_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "12"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P013/ses-S001/eeg/sub-P013_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "13"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P014/ses-S001/eeg/sub-P014_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "14"
    session_id: "01"
  - path: "/home/owaismujtaba/projects/mind-voice/RawData/sub-P015/ses-S001/eeg/sub-P015_ses-S001_task-Default_run-001_eeg.xdf"
    subject_id: "15"
    session_id: "01"
