dataset:
    create_bids: False
    BIDS_DIR: 'BIDS'
    MONTAGE: 'standard_1020'
    config_path: 'bids_config.yaml'
    EEG_SR: 1000
    AUDIO_SR: 48000

preprocessing:
    EEG_FILTER: {"l_freq": 0.1, "h_freq": 40.0}
    EEG_REFERENCE: ['FCz']
    ICA_PARAMS: {"n_components": 50, "random_state": 97}
    NOTCH: [50, 100]
    
analysis:
    results_dir: 'results'
    p100: False
    decoding: False
    morter: False
    ica: False
    snr: False


anonymize:
    anonymize_audio: False
    pitch_steps: 5
    formant_ratio: 1.3



plotting:
    peak_mean_amplitude: True
    grand_erp_visual_real: True
    accuracy_plots: True
    metrics_plots: True
    confusion_matrix: True
    display_per_class_metrics: True
    plot_snr: False