dataset:
    create_bids: False
    BIDS_DIR: 'BIDS'
    config_path: 'bids_config.yaml'
    EEG_SR: 1024
    AUDIO_SR: 48000


analysis:
    results_dir: 'results'
    p100: False
    eeg_filter:
        low: 0.1
        high: 120

    decoding: True


anonymize:
    anonymize_audio: False
    pitch_steps: 5
    formant_ratio: 1.3


plotting:
    peak_mean_amplitude: False
    grand_erp_visual_real: False