dataset:
    create_bids: False
    BIDS_DIR: 'BIDS'
    config_path: 'bids_config.yaml'
    EEG_SR: 1024
    AUDIO_SR: 48000


analysis:
    results_dir: 'results'
    p100: False
    eeg_filter:
        low: 0.1
        high: 120

    decoding: False


anonymize:
    anonymize_audio: False
    pitch_steps: 5
    formant_ratio: 1.3


plotting:
    peak_mean_amplitude: True
    grand_erp_visual_real: True
    accuracy_plots: True
    metrics_plots: True
    confusion_matrix: True
    display_per_class_metrics: True